version: '3.8'
services:
  syndicate_old:
    build: .
    image: syndicate_old:local
    container_name: syndicate_old
    volumes:
      - ..:/opt/syndicate_old:cached
    working_dir: /opt/syndicate
    command: bash -c "./scripts/start_executor.sh"
    environment:
      - METRICS_PORT=8080
      - OLLAMA_HOST=http://host.docker.internal:11434
    ports:
      - "8080:8080"

  prometheus:
    image: prom/prometheus:latest
    container_name: gold_prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:9.5.0
    container_name: gold_grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana
